name: Lint

on:
  push:
  pull_request:

concurrency: lint-${{ github.sha }}

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON_VERSION: "3.11"
    steps:
      - name: Check out repository.
        uses: actions/checkout@v3

      - name: Set up Python ${{ env.PYTHON_VERSION }}.
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies.
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run pre-commit hooks.
        uses: pre-commit/action@v3.0.0
